name: format-checks

on:
  pull_request:
jobs:
  config-format-checks:
    runs-on: ubuntu-latest
    env: 
      ref: ${{github.ref}}
      path: ${{github.path}}
      base_ref: ${{github.base_ref}}
    steps:
      - name: "Files in PR"
        run: echo "$files"
      
      
